#include "leg_task.h"

void VMC_data_get(leg_state_t *leg , float phi1_angle, 
                                     float phi1_gyro,
                                     float phi4_angle,
                                     float phi4_gyro)
{


 leg->last_dl0 = leg->this_dl0;

 leg->phi4 = phi4_angle+PI;
 leg->phi1 = phi1_angle+PI;

 leg->dphi4 = phi4_gyro;
 leg->dphi1 = phi1_gyro;

 leg_pos(leg->phi1, leg->phi4, leg->pos);

 leg->l0   = leg->pos[0];
 leg->phi0 = leg->pos[1];

 leg_spd(leg->dphi1, leg->dphi4, leg->phi1, leg->phi4, leg->spd);
 leg->dl0  = leg->spd[0];
 leg->this_dl0= leg->dl0;

 leg->dphi0 = leg->spd[1];
    leg->ddl0 = (leg->this_dl0 - leg->last_dl0) / (TIME_STEP * 0.001);
//    leg->last_dl0 = leg->this_dl0;
//    leg->phi4 = phi4_angle;
//    leg->phi1 = phi1_angle;
//    leg->dphi4 = phi4_gyro;
//    leg->dphi1 = phi1_gyro;

//    leg_pos(leg->phi1, leg->phi4, leg->pos);
//    leg->l0 = leg->pos[0];
//    leg->phi0 = leg->pos[1];
//    leg_spd(leg->dphi1, leg->dphi4, leg->phi1, leg->phi4, leg->spd);
//    leg->dl0 = leg->spd[0];
//    leg->this_dl0 = leg->dl0;
//    leg->dphi0 = leg->spd[1];
//    leg->ddl0 = (leg->this_dl0 - leg->last_dl0) / (TIME_STEP * 0.001);//可能要加低通滤波器

    leg_J_cal(phi1_angle,phi4_angle,leg->J);
    for (int i = 0; i < 2; i++)
    {
        for (int j = 0; j < 2; j++)
        {
            
                leg->j[j][i] = leg->J[i * 2 + j];
            
            
        }
            
    }

    
}

//定义矩阵
mat Jacobian,
    JacobianT,
    JacobinT_inv,
    mat_F,
    mat_T;
    

static float  Jacobian_data[4];
static float  JacobianT_data[4];
static float  JacobinT_inv_data[4];
static float  mat_F_data[2];
static float  mat_T_data[2];

void FN_calculate(leg_state_t *leg,float MT1_torque,float MT4_torque,Lpf1stObj *ft)
{
    float costheta = cosf(b_chassis.balance_loop.theta);
    float sintheta = sinf(b_chassis.balance_loop.theta);

    //dtheta的计算
    static float this_dtheta, last_dtheta;
      last_dtheta = this_dtheta;
      this_dtheta = b_chassis.balance_loop.dtheta;
      b_chassis.balance_loop.ddtheta = (this_dtheta - last_dtheta) / ((TIME_STEP * 0.001));
    //ddzw的计算
      float ddzw = b_chassis.balance_loop.ddz - leg->ddl0 * costheta + \
                  2 * leg->dl0 * b_chassis.balance_loop.dtheta * sintheta + \
                    leg->l0 * b_chassis.balance_loop.ddtheta * sintheta + \
                    leg->l0 * (b_chassis.balance_loop.dtheta * b_chassis.balance_loop.dtheta) * costheta;
			
      leg->ddzw = ddzw;
	//		Lpf_1st_calcu(ft,ddzw,5,0.002);// 计算一阶低通滤波器的输出值，并返回
    //P和Tp的计算
    mat_init(&Jacobian,2,2,(float *)Jacobian_data);
    mat_init(&JacobianT,2,2,(float *)JacobianT_data);
    mat_init(&JacobinT_inv,2,2,(float *)JacobinT_inv_data);
    mat_init(&mat_F,2,1,(float *)mat_F_data);
    mat_init(&mat_T,2,1,(float *)mat_T_data);

    Jacobian_data[0] = leg->j[0][0];
    Jacobian_data[1] = leg->j[0][1];
    Jacobian_data[2] = leg->j[1][0];
    Jacobian_data[3] = leg->j[1][1];

    mat_T_data[0] = MT1_torque;
    mat_T_data[1] = MT4_torque;

    //求得VMC逆转换矩阵
    // FTp = (J')\[MT1;MT4];
    mat_trans(&Jacobian,&JacobianT);//求得J的转置
    mat_inv(&JacobianT,&JacobinT_inv);//求得J的逆
    mat_mult(&JacobinT_inv,&mat_T,&mat_F);//求得J的逆和T的乘积

    leg->F_fdb = mat_F.pData[0];
		leg->temp_spring =leg->F_fdb - leg->spring_FN;
    leg->Tp_fdb = mat_F.pData[1];

    float P = leg->temp_spring*costheta + (leg->Tp_fdb*sintheta)/leg->l0;
    //支持力的计算
    leg->leg_FN = WHEEL_MASS * leg->ddzw + P + WHEEL_MASS * 9.81;

      
      
}

/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : double phi1
 *                double phi4
 *                double pos[2]
 * Return Type  : void
*/
void leg_pos(float phi1, float phi4, float pos[2])
{
  float t11;
  float t12;
  float t14;
  float t15;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  float t8;
  /* LEG_POS */
  /*     POS = LEG_POS(PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:19 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t6 = t2 * 0.21F;
  t8 = t4 * 0.21F;
  t11 = t2 * 0.1008F;
  t12 = t3 * 0.1008F;
  t14 = t4 * 0.1008F;
  t15 = t5 * 0.1008F;
  t4 = t6 - t3 * 0.21F;
  t2 = t8 - t5 * 0.21F;
  t3 = t11 - t12;
  t5 = t14 - t15;
  t2 = t4 * t4 + t2 * t2;
  t2 = atanf(1.0F / ((t12 - t11) + t2) *
             ((t15 - t14) + sqrtf((t3 * t3 + t5 * t5) - t2 * t2))) *
       2.0F;
  t4 = t8 + sinf(t2) * 0.24F;
  t2 = t6 + cosf(t2) * 0.24F;
  pos[0] = sqrtf(t4 * t4 + t2 * t2);
  pos[1] = atan2f(t4, t2);
}



/*
 * File trailer for leg_pos.c
 *
 * [EOF]
 */

void leg_spd(float dphi1, float dphi4, float phi1, float phi4, float spd[2])
{
  float t10;
  float t12;
  float t15;
  float t16;
  float t18;
  float t19;
  float t2;
  float t29;
  float t3;
  float t30;
  float t33;
  float t34;
  float t37;
  float t38;
  float t39;
  float t4;
  float t40;
  float t5;
  float t51;
  float t59;
  float t60;
  float t62;
  float t66;
  float t73;
  /* LEG_SPD */
  /*     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:21 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10 = t2 * 0.21F;
  t12 = t4 * 0.21F;
  t15 = t2 * 0.1008F;
  t16 = t3 * 0.1008F;
  t18 = t4 * 0.1008F;
  t19 = t5 * 0.1008F;
  t29 = t10 - t3 * 0.21F;
  t30 = t12 - t5 * 0.21F;
  t33 = t15 - t16;
  t34 = t18 - t19;
  t37 = t4 * t29 * 0.42F;
  t38 = t5 * t29 * 0.42F;
  t39 = t2 * t30 * 0.42F;
  t40 = t3 * t30 * 0.42F;
  t51 = t29 * t29 + t30 * t30;
  t59 = 1.0F / ((t16 - t15) + t51);
  t60 = t59 * t59;
  t62 = sqrtf((t33 * t33 + t34 * t34) - t51 * t51);
  t29 = 1.0F / t62;
  t66 = (t19 - t18) + t62;
  t73 = atanf(t59 * t66) * 2.0F;
  t30 = cosf(t73);
  t62 = sinf(t73);
  t73 = 1.0F / (t60 * (t66 * t66) + 1.0F);
  t18 = ((t18 + t39) - t37) * t60 * t66 +
        t59 * (t15 - t29 *
                         ((t2 * t34 * 0.2016F - t4 * t33 * 0.2016F) +
                          t51 * (t37 - t39) * 2.0F) /
                         2.0F);
  t29 = ((t19 + t40) - t38) * t60 * t66 +
        t59 * (t16 - t29 *
                         ((t3 * t34 * 0.2016F - t5 * t33 * 0.2016F) +
                          t51 * (t38 - t40) * 2.0F) /
                         2.0F);
  t2 = t10 + t30 * 0.24F;
  t4 = t12 + t62 * 0.24F;
  t66 = t30 * t73;
  t15 = t66 * t29;
  t62 *= t73;
  t51 = t62 * t29;
  t59 = t2 * t2;
  t60 = 1.0F / t2;
  t30 = t4 * t4 + t59;
  t29 = 1.0F / sqrtf(t30);
  t73 = 1.0F / t30;
  t66 = t10 - t66 * t18 * 0.48F;
  t30 = t12 - t62 * t18 * 0.48F;
  spd[0] = dphi4 * t29 * (t4 * t15 * 0.96F - t2 * t51 * 0.96F) / 2.0F +
           dphi1 * t29 * (t4 * t66 * 2.0F - t2 * t30 * 2.0F) / 2.0F;
  t29 = t4 * (1.0F / t59);
  spd[1] =
      dphi1 * t59 * t73 * (t60 * t66 + t29 * t30) -
      dphi4 * t59 * t73 * (t60 * (0.0F - t15 * 0.48F) - t29 * (t51 * 0.48F));
}
/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,Tp,PHI1,PHI4)
 *
 * Arguments    : double F
 *                double Tp
 *                double phi1
 *                double phi4
 *                double T[2]
 * Return Type  : void
 */
void leg_conv(float F, float Tp, float phi1, float phi4, float T[2])
{
  float t110;
  float t112;
  float t118;
  float t130;
  float t133;
  float t141;
  float t16;
  float t18;
  float t21;
  float t22;
  float t24;
  float t25;
  float t4;
  float t49;
  float t5;
  float t50;
  float t55;
  float t56;
  float t6;
  float t63;
  float t64;
  float t65;
  float t66;
  float t7;
  float t91;
  /* LEG_CONV */
  /*     T = LEG_CONV(F,Tp,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:22 */
  t4 = cosf(phi1);
  t5 = cosf(phi4);
  t6 = sinf(phi1);
  t7 = sinf(phi4);
  t16 = t4 * 0.21F;
  t18 = t6 * 0.21F;
  t21 = t4 * 0.1008F;
  t22 = t5 * 0.1008F;
  t24 = t6 * 0.1008F;
  t25 = t7 * 0.1008F;
  t49 = t16 - t5 * 0.21F;
  t50 = t18 - t7 * 0.21F;
  t55 = t21 - t22;
  t56 = t24 - t25;
  t63 = t6 * t49 * 0.42F;
  t64 = t7 * t49 * 0.42F;
  t65 = t4 * t50 * 0.42F;
  t66 = t5 * t50 * 0.42F;
  t91 = t49 * t49 + t50 * t50;
  t49 = 1.0F / ((t22 - t21) + t91);
  t50 = t49 * t49;
  t110 = sqrtf((t55 * t55 + t56 * t56) - t91 * t91);
  t112 = 1.0F / t110;
  t118 = (t25 - t24) + t110;
  t130 = atanf(t49 * t118) * 2.0F;
  t133 = cosf(t130);
  t130 = sinf(t130);
  t141 = 1.0F / (t50 * (t118 * t118) + 1.0F);
  t110 = ((t24 + t65) - t63) * t50 * t118 +
         t49 * (t21 - t112 *
                          ((t4 * t56 * 0.2016F - t6 * t55 * 0.2016F) +
                           t91 * (t63 - t65) * 2.0F) /
                          2.0F);
  t6 = ((t25 + t66) - t64) * t50 * t118 +
       t49 * (t22 - t112 *
                        ((t5 * t56 * 0.2016F - t7 * t55 * 0.2016F) +
                         t91 * (t64 - t66) * 2.0F) /
                        2.0F);
  t21 = t16 + t133 * 0.24F;
  t24 = t18 + t130 * 0.24F;
  t112 = t21 * t21;
  t63 = 1.0F / t21;
  t118 = t24 * t24 + t112;
  t4 = t133 * t141;
  t91 = t16 - t4 * t110 * 0.48F;
  t130 *= t141;
  t50 = t18 - t130 * t110 * 0.48F;
  t110 = F * (1.0F / sqrtf(t118));
  t49 = Tp * t112 * (1.0F / t118);
  t118 = t24 * (1.0F / t112);
  T[0] = t110 * (t24 * t91 * 2.0F - t21 * t50 * 2.0F) / 2.0F +
         t49 * (t63 * t91 + t118 * t50);
  T[1] = t110 * (t4 * t24 * t6 * 0.96F - t130 * t21 * t6 * 0.96F) / 2.0F -
         t49 * (t63 * (0.0F - t4 * t6 * 0.48F) - t118 * (t130 * t6 * 0.48F));
}
/* Function Definitions */
/*
 * leg_J_cal
 *     J = leg_J_cal(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float J[4]
 * Return Type  : void
 */
void leg_J_cal(float phi1, float phi4, float J[4])
{
 float t10_tmp;
  float t12;
  float t13;
  float t14_tmp;
  float t16;
  float t17;
  float t2;
  float t29;
  float t3;
  float t30;
  float t31;
  float t32;
  float t37;
  float t38;
  float t39;
  float t4;
  float t40;
  float t5;
  float t51;
  float t57;
  float t58;
  float t63;
  float t66;
  float t81;
  /* leg_four_bar_J_cal */
  /*     J = leg_four_bar_J_cal(PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2025-03-05 19:19:34 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10_tmp = t2 * 0.21F;
  t12 = t2 * 0.105F;
  t13 = t3 * 0.105F;
  t14_tmp = t4 * 0.21F;
  t16 = t4 * 0.105F;
  t17 = t5 * 0.105F;
  t29 = t10_tmp - t3 * 0.21F;
  t30 = t12 - t13;
  t31 = t14_tmp - t5 * 0.21F;
  t32 = t16 - t17;
  t37 = t4 * t29 * 0.42F;
  t38 = t5 * t29 * 0.42F;
  t39 = t2 * t31 * 0.42F;
  t40 = t3 * t31 * 0.42F;
  t51 = t29 * t29 + t31 * t31;
  t57 = 1.0F / ((t13 - t12) + t51);
  t58 = t57 * t57;
  t2 = sqrtf((t30 * t30 + t32 * t32) - t51 * t51);
  t63 = 1.0F / t2;
  t66 = (t17 - t16) + t2;
  t2 = atanf(t57 * t66) * 2.0F;
  t29 = cosf(t2);
  t31 = sinf(t2);
  t81 = 1.0F / (t58 * (t66 * t66) + 1.0F);
  t37 = t58 * ((t16 + t39) - t37) * t66 +
        t57 * (t12 - t63 *
                         ((t10_tmp * t32 + t4 * t30 * -0.21F) +
                          t51 * (t37 - t39) * 2.0F) /
                         2.0F);
  t2 = t58 * ((t17 + t40) - t38) * t66 +
       t57 * (t13 - t63 *
                        ((t5 * t30 * -0.21F + t51 * (t38 - t40) * 2.0F) +
                         t3 * t32 * 0.21F) /
                        2.0F);
  t12 = t10_tmp + t29 / 4.0F;
  t16 = t14_tmp + t31 / 4.0F;
  t51 = t29 * t81;
  t4 = t51 * t2;
  t31 *= t81;
  t57 = t31 * t2;
  t58 = t12 * t12;
  t63 = 1.0F / t12;
  t29 = t16 * t16 + t58;
  t39 = 1.0F / sqrtf(t29);
  t66 = 1.0F / t29;
  t51 = t10_tmp - t51 * t37 / 2.0F;
  t2 = t14_tmp - t31 * t37 / 2.0F;
  J[0] = t39 * (t16 * t51 * 2.0F - t12 * t2 * 2.0F) / 2.0F;
  t29 = t16 * (1.0F / t58);
  J[1] = t58 * t66 * (t63 * t51 + t29 * t2);
  J[2] = t39 * (t16 * t4 - t12 * t57) / 2.0F;
  J[3] = -t58 * t66 * (t63 * (0.0F - t4 / 2.0F) - t29 * (t57 / 2.0F));
}

/*
 * File trailer for leg_J_cal.c
 *
 * [EOF]
 */
